#ifndef SETTINGSSPACESHOOTER_H
#define SETTINGSSPACESHOOTER_H


#define WINDOW_WIDTH 1920
#define WINDOW_HEIGHT 1080
#define BG_COLOR {15,10,25,255}
#define PLAYER_SPEED 500
#define LASER_SPEED 600
#define METEOR_SPEED_MAX 1000
#define METEOR_SPEED_MIN 200
#define METEOR_TIMER_DURATION 0.4
#define FONT_SIZE 120
#define NUM_STARS 30
#define MAX_LASERS 60
#define MAX_TIME 100
#define POWERUP_TIMER_DURATION ((rand() % 8) + 12)
#define POWER_DISCARD_TIMER ((rand() % 5) + 10)
#define NUM_AVAILABLE_POWERUPS 2
#define SHIELD_RADIUS_ADDITION 50
#define NUM_EXPLOSION_FRAMES 12

#endif
